In [27]:
import numpy as np
import random

# 6. Test for Infinity

## Write a NumPy program to test elements-wise for positive or negative infinity. 

In [4]:
arr1 = np.array([1,2,3,np.inf,4,5,6,-np.inf])
res_pos = np.isposinf(arr1) # check positive infinity
print('Positive infinity',res_pos)

res_neg = np.isneginf(arr1) # check negative infinity
print('Negative infinity',res_neg)

Positive infinity [False False False  True False False False False]
Negative infinity [False False False False False False False  True]


# 7. Test for NaN

## Write a NumPy program to test element-wise for NaN of a given array.

In [12]:
arr1 = np.array([1,np.nan,2,np.nan,4,6])
arr1

array([ 1., nan,  2., nan,  4.,  6.])

In [11]:
res=np.isnan(arr1)
print(res)

[False  True False  True False False]


## Replace all NaN values in an array with the average of its non-NaN elements.

In [13]:
arr1 = np.array([1,2,np.nan, 4,5,np.nan])
arr1

array([ 1.,  2., nan,  4.,  5., nan])

In [17]:
mean_nan = np.nanmean(arr1) #nanmean() mean of all non nan elements, it ignores nan values
mean_nan

3.0

In [24]:
new_arr = np.where(np.isnan(arr1),mean_nan, arr1)  # syntax of where(condition [,x,y]), it returns index of the satisfied condition, it returns x if True else y
new_arr

array([1., 2., 3., 4., 5., 3.])

## Find and return the indices of NaN values in a large 2D array.

In [18]:
arr_2D = np.array([[1,2,np.nan,3],[np.nan,4,5,np.nan]])
arr_2D

array([[ 1.,  2., nan,  3.],
       [nan,  4.,  5., nan]])

In [23]:
new_arr_index = np.where(np.isnan(arr_2D))
print(new_arr_index) # need to zip both index arrays to find the real indices
print(list(zip(new_arr_index[0],new_arr_index[1])))

(array([0, 1, 1]), array([2, 0, 3]))
[(0, 2), (1, 0), (1, 3)]


## Count the total number of NaN entries in a randomly generated array.

In [33]:
rand_arr = np.random.rand(5,5)
print(rand_arr)
rand_arr[2,3] = np.nan
rand_arr[4,1] = np.nan
print('After nan')
print(rand_arr)
print(np.isnan(rand_arr))
print(np.count_nonzero(np.isnan(rand_arr))) # count_nonzero(arr) counts non-zero elements in the array and it works along axis, axis=0 check columns, axis=1 is rows

[[0.12174562 0.86135831 0.44605662 0.83766139 0.08385317]
 [0.08131212 0.73878558 0.94387154 0.45034112 0.58184407]
 [0.52346115 0.89672779 0.21393838 0.84815627 0.73043943]
 [0.90422949 0.72256427 0.67609765 0.46138116 0.93602504]
 [0.18287254 0.6562311  0.31659901 0.8154666  0.34164588]]
After nan
[[0.12174562 0.86135831 0.44605662 0.83766139 0.08385317]
 [0.08131212 0.73878558 0.94387154 0.45034112 0.58184407]
 [0.52346115 0.89672779 0.21393838        nan 0.73043943]
 [0.90422949 0.72256427 0.67609765 0.46138116 0.93602504]
 [0.18287254        nan 0.31659901 0.8154666  0.34164588]]
[[False False False False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]
 [False  True False False False]]
2


## Use masking to extract and list only the NaN elements from an array.

In [41]:
print(rand_arr) # original array
nan_arr = np.isnan(rand_arr) # get all nan bool array
print(nan_arr)
print(rand_arr[nan_arr]) # get values at that bool array using index at array

[[0.12174562 0.86135831 0.44605662 0.83766139 0.08385317]
 [0.08131212 0.73878558 0.94387154 0.45034112 0.58184407]
 [0.52346115 0.89672779 0.21393838        nan 0.73043943]
 [0.90422949 0.72256427 0.67609765 0.46138116 0.93602504]
 [0.18287254        nan 0.31659901 0.8154666  0.34164588]]
[[False False False False False]
 [False False False False False]
 [False False False  True False]
 [False False False False False]
 [False  True False False False]]
[nan nan]


# 8. Test for Complex/Real/Scalar

## Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 

In [43]:
arr1 = np.array([1,2,3,4+5j,3.4])
print(arr1)

[1. +0.j 2. +0.j 3. +0.j 4. +5.j 3.4+0.j]


In [44]:
type(arr1)

numpy.ndarray

In [45]:
arr1.dtype

dtype('complex128')

#### create complex array using dtype = 'complex'

In [48]:
comp_arr = np.array([1,2,3], dtype='complex')

In [56]:
comp_arr1 = np.array([1,2,3+4j,5,9+4j])
comp_arr1

array([1.+0.j, 2.+0.j, 3.+4.j, 5.+0.j, 9.+4.j])

In [57]:
#check iscomplex
res_comp = np.iscomplex(comp_arr1)
res_comp

array([False, False,  True, False,  True])

In [62]:
#check if real using isreal
res_real = np.isreal(comp_arr1)
res_real

array([ True,  True, False,  True, False])

In [63]:
#check if it is scalar
res_scalar = np.isscalar(3.1)
res_scalar

True

In [64]:
#check array if it is scalar
res_scal_arr = np.isscalar([4.6])
res_scal_arr

False

# 9. Test Element-Wise Tolerance Equality

## Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [65]:
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))


False


In [66]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([1.00001, 2.00002, 3.00003])
c = np.array([1.1, 2.2, 3.3])
print(np.allclose(a,b))

True


In [67]:
print(np.allclose(a,c))

False


In [69]:
print(np.allclose(a,c,rtol=0.2,atol=0.2)) #rtol is relative tolerance(default 1e-05),atol absolute tolerance(default 1e-08)

True


# 10. Element-Wise Comparison (Greater/Less)

## Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [74]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,3,3])
#Greater
print('Array1 is greater than Array2')
print(arr1>arr2)
#Less than
print('Array1 is less than Array2')
print(arr1<arr2)
#Greater Equal to
print('Array1 is greater than equal to Array2')
print(arr1 >= arr2)
print('Array 1 is less than equal to Array2')
print(arr1<=arr2)

Array1 is greater than Array2
[False False False]
Array1 is less than Array2
[False  True False]
Array1 is greater than equal to Array2
[ True False  True]
Array 1 is less than equal to Array2
[ True  True  True]
