Numpy exercise

Create and print array in NumPy

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


Find the shape of array

In [5]:
print('shape of array', arr.shape)

shape of array (5,)


Create 2-dimensional array and print it's shape

In [7]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print('Array is---',arr_2d)
print('Shape of array is ---', arr_2d.shape)

Array is--- [[1 2 3]
 [4 5 6]]
Shape of array is --- (2, 3)


Create one 2-d array and multiply it's elements by 10

In [8]:
arr_1d = np.array([[1,2,3], [4,5,6]])
print('The array is ', arr_1d)
multiplied_arr = arr_1d*10
print('Multiplied array', multiplied_arr)

The array is  [[1 2 3]
 [4 5 6]]
Multiplied array [[10 20 30]
 [40 50 60]]


Create two 2D arrays and multiply them

In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,3,5],[7,9,11]])
print('array 1', arr1.shape)
print(arr1)
print('array 2', arr2.shape)
print(arr2)
multiplied_array = arr1*arr2
print('Multiplied array')
print(multiplied_array)

array 1 (2, 3)
[[1 2 3]
 [4 5 6]]
array 2 (2, 3)
[[ 1  3  5]
 [ 7  9 11]]
Multiplied array
[[ 1  6 15]
 [28 45 66]]


COPY ARRAY FROM ANOTHER ARRAY AND CHECK IF IT IS A VIEW OR COPY

In [23]:
arr1 = np.array([1,2,3])
print(arr1)
copy_arr1 = arr1.copy()
print(copy_arr1)
print(copy_arr1.base) #base None means it owns the data and changes to copied array will not be reflected in the original array
copy_arr1[2]=10
print('Original array', arr1)
print('Copied array after changes',copy_arr1)

[1 2 3]
[1 2 3]
None
Original array [1 2 3]
Copied array after changes [ 1  2 10]


SLICING IN NUMPY ARRAY, ALSO CHECK IT IS A VIEW OR COPY, OWNS DATA OR NOT

In [27]:
arr = np.array([1,2,3,4,5])
sliced_arr = arr[1:3]
print(sliced_arr)
print(sliced_arr.base)

[2 3]
[1 2 3 4 5]
